// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package mike_gama_coupling;

@net.sf.jni4net.attributes.ClrType
public class Mike_Data extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Mike_Data(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Mike_Data() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        mike_gama_coupling.Mike_Data.__ctorMike_Data0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorMike_Data0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;)LSystem/String;")
    public native java.lang.String Dfs0File_Read_Data(java.lang.String filename, java.lang.String gate_name);
    
    public static system.Type typeof() {
        return mike_gama_coupling.Mike_Data.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        mike_gama_coupling.Mike_Data.staticType = staticType;
    }
    //</generated-proxy>
}
