//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAS506 {
    
    
    #region Component Designer generated code 
    public partial class @__HECRASController_ComputeCompleteEventHandler_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::RAS506.____HECRASController_ComputeCompleteEventHandler.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::RAS506.@__HECRASController_ComputeCompleteEventHandler), typeof(global::RAS506.@__HECRASController_ComputeCompleteEventHandler_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::RAS506.@__HECRASController_ComputeCompleteEventHandler), typeof(global::RAS506.@__HECRASController_ComputeCompleteEventHandler_))]
    internal sealed partial class ____HECRASController_ComputeCompleteEventHandler : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_Invoke0;
        
        private ____HECRASController_ComputeCompleteEventHandler(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::RAS506.____HECRASController_ComputeCompleteEventHandler.staticClass = @__class;
            global::RAS506.____HECRASController_ComputeCompleteEventHandler.j4n_Invoke0 = @__env.GetMethodID(global::RAS506.____HECRASController_ComputeCompleteEventHandler.staticClass, "Invoke", "()V");
        }
        
        public void Invoke() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::RAS506.____HECRASController_ComputeCompleteEventHandler.j4n_Invoke0);
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(____HECRASController_ComputeCompleteEventHandler);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Invoke", "Invoke0", "()V"));
            return methods;
        }
        
        private static void Invoke0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RAS506.@__HECRASController_ComputeCompleteEventHandler @__real = global::net.sf.jni4net.utils.Convertor.StrongJ2CpDelegate<global::RAS506.@__HECRASController_ComputeCompleteEventHandler>(@__env, @__obj);
            @__real.Invoke();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::RAS506.____HECRASController_ComputeCompleteEventHandler(@__env);
            }
        }
    }
    #endregion
}
