//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAS506 {
    
    
    #region Component Designer generated code 
    public partial class _HECRASFlow_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::RAS506.___HECRASFlow.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::RAS506._HECRASFlow), typeof(global::RAS506._HECRASFlow_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::RAS506._HECRASFlow), typeof(global::RAS506._HECRASFlow_))]
    internal sealed partial class ___HECRASFlow : global::java.lang.Object, global::RAS506._HECRASFlow {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_UnsteadyBoundaryIndex0;
        
        private ___HECRASFlow(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::RAS506.___HECRASFlow.staticClass = @__class;
            global::RAS506.___HECRASFlow.j4n_UnsteadyBoundaryIndex0 = @__env.GetMethodID(global::RAS506.___HECRASFlow.staticClass, "UnsteadyBoundaryIndex", "(Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;" +
                    "Lnet/sf/jni4net/Ref;)I");
        }
        
        public int UnsteadyBoundaryIndex(string River, string Reach, string Rs, string StorageArea, string Connection) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 20)){
            return ((int)(@__env.CallIntMethod(this, global::RAS506.___HECRASFlow.j4n_UnsteadyBoundaryIndex0, global::net.sf.jni4net.utils.Convertor.ParStrongC2Jp<string>(@__env, River), global::net.sf.jni4net.utils.Convertor.ParStrongC2Jp<string>(@__env, Reach), global::net.sf.jni4net.utils.Convertor.ParStrongC2Jp<string>(@__env, Rs), global::net.sf.jni4net.utils.Convertor.ParStrongC2Jp<string>(@__env, StorageArea), global::net.sf.jni4net.utils.Convertor.ParStrongC2Jp<string>(@__env, Connection))));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(___HECRASFlow);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "UnsteadyBoundaryIndex", "UnsteadyBoundaryIndex0", "(Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;" +
                        "Lnet/sf/jni4net/Ref;)I"));
            return methods;
        }
        
        private static int UnsteadyBoundaryIndex0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle River, global::net.sf.jni4net.utils.JniLocalHandle Reach, global::net.sf.jni4net.utils.JniLocalHandle Rs, global::net.sf.jni4net.utils.JniLocalHandle StorageArea, global::net.sf.jni4net.utils.JniLocalHandle Connection) {
            // (Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;)I
            // (LSystem/String;LSystem/String;LSystem/String;LSystem/String;LSystem/String;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            string @__ref_River = net.sf.jni4net.Ref.GetValue<string>(@__env, River);
            string @__ref_Reach = net.sf.jni4net.Ref.GetValue<string>(@__env, Reach);
            string @__ref_Rs = net.sf.jni4net.Ref.GetValue<string>(@__env, Rs);
            string @__ref_StorageArea = net.sf.jni4net.Ref.GetValue<string>(@__env, StorageArea);
            string @__ref_Connection = net.sf.jni4net.Ref.GetValue<string>(@__env, Connection);
            global::RAS506._HECRASFlow @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RAS506._HECRASFlow>(@__env, @__obj);
            @__return = ((int)(@__real.UnsteadyBoundaryIndex(ref __ref_River, ref __ref_Reach, ref __ref_Rs, ref __ref_StorageArea, ref __ref_Connection)));
            net.sf.jni4net.Ref.SetValue<string>(@__env, River, @__ref_River);
            net.sf.jni4net.Ref.SetValue<string>(@__env, Reach, @__ref_Reach);
            net.sf.jni4net.Ref.SetValue<string>(@__env, Rs, @__ref_Rs);
            net.sf.jni4net.Ref.SetValue<string>(@__env, StorageArea, @__ref_StorageArea);
            net.sf.jni4net.Ref.SetValue<string>(@__env, Connection, @__ref_Connection);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::RAS506.___HECRASFlow(@__env);
            }
        }
    }
    #endregion
}
