//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HecRas_Gama_Coupling {
    
    
    #region Component Designer generated code 
    public partial class HecRas_Data_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::HecRas_Gama_Coupling.@__HecRas_Data.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::HecRas_Gama_Coupling.HecRas_Data), typeof(global::HecRas_Gama_Coupling.HecRas_Data_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::HecRas_Gama_Coupling.HecRas_Data), typeof(global::HecRas_Gama_Coupling.HecRas_Data_))]
    internal sealed partial class @__HecRas_Data : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__HecRas_Data(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::HecRas_Gama_Coupling.@__HecRas_Data.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__HecRas_Data);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ReadData", "ReadData0", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorHecRas_Data0", "__ctorHecRas_Data0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static void ReadData0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::HecRas_Gama_Coupling.HecRas_Data @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::HecRas_Gama_Coupling.HecRas_Data>(@__env, @__obj);
            @__real.ReadData();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorHecRas_Data0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::HecRas_Gama_Coupling.HecRas_Data @__real = new global::HecRas_Gama_Coupling.HecRas_Data();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::HecRas_Gama_Coupling.@__HecRas_Data(@__env);
            }
        }
    }
    #endregion
}
