language: java
jdk:
  - oraclejdk8
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" >> ~/.mavenrc
notifications:
  email: false
addons:
    apt:
        packages:
            - sshpass
    ssh_known_hosts:
      - 51.255.46.42
cache:
  directories:
  - "$HOME/.m2"
script: sh ./build.sh
after_success: 
    - export SSHPASS=$USER_PWD 
    - sh ./publish.sh
branches:
  only:
    - master
