language: java
jdk:
  - oraclejdk8
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" >> ~/.mavenrc
notifications:
  email: false
cache:
  directories:
  - "$HOME/.m2/cache"
script: 
  - travis encrypt -r hqnghi88/gamaExpClone "CI_DEPLOY_USERNAME=hqnghi88"
  - travis encrypt -r hqnghi88/gamaExpClone "CI_DEPLOY_PASSWORD=23111988"
  - sh ./build.sh
branches:
  only:
    - master
