// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package ras506;

@net.sf.jni4net.attributes.ClrType
public abstract class __HECRASController_ComputeProgressEventEventHandler extends system.MulticastDelegate {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected __HECRASController_ComputeProgressEventEventHandler(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected __HECRASController_ComputeProgressEventEventHandler() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(F)V")
    public abstract void Invoke(float Progress);
    
    public static system.Type typeof() {
        return ras506.__HECRASController_ComputeProgressEventEventHandler.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        ras506.__HECRASController_ComputeProgressEventEventHandler.staticType = staticType;
    }
    //</generated-proxy>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class ____HECRASController_ComputeProgressEventEventHandler extends ras506.__HECRASController_ComputeProgressEventEventHandler {
    
    protected ____HECRASController_ComputeProgressEventEventHandler(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(F)V")
    public native void Invoke(float Progress);
}
//</generated-proxy>
