// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package ras506;

@net.sf.jni4net.attributes.ClrInterface
public interface _HECRASFlow {
    
    //<generated-interface>
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LSystem/String;LSystem/String;LSystem/String;)I")
    int UnsteadyBoundaryIndex(net.sf.jni4net.Ref<java.lang.String> River, net.sf.jni4net.Ref<java.lang.String> Reach, net.sf.jni4net.Ref<java.lang.String> Rs, net.sf.jni4net.Ref<java.lang.String> StorageArea, net.sf.jni4net.Ref<java.lang.String> Connection);
    //</generated-interface>
}
