source.. = src/,\
           gaml/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               models/,\
               lib/tutorials-1.0.0-beta4-jar-with-dependencies.jar
			   