#!/bin/bash
export GAMA_HEADLESS_HOME=../../../gama/gama.product/target/products/gama.headless.product/linux/gtk/x86_64

# Create the directory first
mkdir -p output.log

MY_WS=/tmp/gama_ws_${OMPI_COMM_WORLD_RANK:-0}
mkdir -p $MY_WS

mpirun \
    --mca mpi_show_handle_leaks 1 \
    -display-map \
    -np $2 \
    --output-filename output.log/mpi_log/t \
    --merge-stderr-to-stdout \
    java \
    -Xms512m -Xmx4g \
    -Djava.awt.headless=true \
    -Djava.security.egd=file:/dev/./urandom \
    -cp $GAMA_HEADLESS_HOME/plugins/org.eclipse.equinox.launcher*.jar \
    --add-exports=java.base/java.lang=ALL-UNNAMED \
    --add-exports=java.desktop/sun.awt=ALL-UNNAMED \
    --add-exports=java.desktop/sun.java2d=ALL-UNNAMED \
    --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED \
    --add-exports=java.base/java.math=ALL-UNNAMED \
    --add-exports=java.base/sun.nio.ch=ALL-UNNAMED \
    --add-opens=java.base/java.lang=ALL-UNNAMED \
    --add-opens=java.base/jdk.internal.loader=ALL-UNNAMED \
    --add-opens=java.base/java.math=ALL-UNNAMED \
    --add-opens=java.base/java.util=ALL-UNNAMED \
    --add-opens=java.base/java.util.concurrent=ALL-UNNAMED \
    --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED \
    --add-opens=java.base/java.net=ALL-UNNAMED \
    --add-opens=java.base/java.security=ALL-UNNAMED \
    --add-opens=java.desktop/java.awt=ALL-UNNAMED \
    --add-opens=java.base/java.io=ALL-UNNAMED \
    --add-opens=java.base/java.time=ALL-UNNAMED \
    --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED \
    --add-opens=java.base/java.text=ALL-UNNAMED \
    --add-opens=java.base/java.lang.ref=ALL-UNNAMED \
    --add-opens=java.sql/java.sql=ALL-UNNAMED \
    --enable-native-access=ALL-UNNAMED \
    org.eclipse.equinox.launcher.Main \
    -configuration $GAMA_HEADLESS_HOME/headless/configuration \
    -application gama.headless.product \
    -data $MY_WS \
    -v $1 output.log