//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hecras_Gama_Coupling {
    
    
    #region Component Designer generated code 
    public partial class hecras_Data_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::hecras_Gama_Coupling.@__hecras_Data.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::hecras_Gama_Coupling.hecras_Data), typeof(global::hecras_Gama_Coupling.hecras_Data_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::hecras_Gama_Coupling.hecras_Data), typeof(global::hecras_Gama_Coupling.hecras_Data_))]
    internal sealed partial class @__hecras_Data : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__hecras_Data(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::hecras_Gama_Coupling.@__hecras_Data.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__hecras_Data);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Dfs0File_Read_Data", "Dfs0File_Read_Data0", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorhecras_Data0", "__ctorhecras_Data0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Dfs0File_Read_Data0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle filename, global::net.sf.jni4net.utils.JniLocalHandle gate_name) {
            // (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
            // (LSystem/String;LSystem/String;)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::hecras_Gama_Coupling.hecras_Data @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::hecras_Gama_Coupling.hecras_Data>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.Dfs0File_Read_Data(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, filename), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, gate_name)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void @__ctorhecras_Data0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::hecras_Gama_Coupling.hecras_Data @__real = new global::hecras_Gama_Coupling.hecras_Data();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::hecras_Gama_Coupling.@__hecras_Data(@__env);
            }
        }
    }
    #endregion
}
