// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package ras506;

@net.sf.jni4net.attributes.ClrInterface
public interface _HECRASController {
    
    //<generated-interface>
    @net.sf.jni4net.attributes.ClrMethod("()V")
    void QuitRas();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    void Compute_ShowComputationWindow();
    
    @net.sf.jni4net.attributes.ClrMethod("(ILSystem/Array;Z)Z")
    boolean Compute_CurrentPlan(net.sf.jni4net.Ref<java.lang.Integer> nmsg, net.sf.jni4net.Ref<system.Array> Msg, net.sf.jni4net.Ref<java.lang.Boolean> BlockingMode);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    void Project_Open(java.lang.String projectFilename);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    void Project_Save();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    void Project_Close();
    //</generated-interface>
}
