// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package hecras_gama_coupling;

@net.sf.jni4net.attributes.ClrType
public class HecRas_Data extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected HecRas_Data(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public HecRas_Data() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        hecras_gama_coupling.HecRas_Data.__ctorHecRas_Data0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorHecRas_Data0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String init_hecras();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/String;")
    public native java.lang.String Project_Open(java.lang.String path);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String Compute_ShowComputationWindow();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String Compute_CurrentPlan();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String Project_Save();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String Project_Close();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String QuitRas();
    
    public static system.Type typeof() {
        return hecras_gama_coupling.HecRas_Data.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        hecras_gama_coupling.HecRas_Data.staticType = staticType;
    }
    //</generated-proxy>
}
