package gama.experimental.markdown.visitors;

import gama.experimental.markdown.markdownSyntactic.IParser;
import gama.experimental.markdown.markdownSyntactic.MarkdownTools;
import gama.gaml.compilation.ast.ISyntacticElement;
import gama.gaml.compilation.ast.ISyntacticElement.SyntacticVisitor;
/**
 * 
 * @author damienphilippon
 * Date : 19 Dec 2017
 * Class representing the visitor of ISyntacticElement representing a Parameter defined in GAML. This visitor
 * will generate the Markdown text for a visited IExpressionDescription for the Documentation
 */
public class VisitorParameters implements SyntacticVisitor{
	/**
	 * Variable that will contain the markdown text generated by the visitor
	 */
	StringBuilder mDText;
	/**
	 * Constructor of the visitor, does not expect anything
	 */
	public VisitorParameters()
	{
	}
	/**
	 * Method used to visit a ISyntacticElement (expecting parameters here), generating the markdown Text of it
	 * @param element {@code ISyntacticElement}, the ISyntacticElement representing a Parameter that will be used to generate the markdown code
	 */
	public void visit(ISyntacticElement element) {
		if(element.getKeyword().equals("parameter"))
		{
			VisitorDebug.DEBUG("          doing parameter "+element.getName());
			mDText.append(MarkdownTools.goBeginLine());
			mDText.append(IParser.MARKDOWN_KEYWORD_LIST+IParser.MARKDOWN_KEYWORD_SPACE+element.getName());
			mDText.append(MarkdownTools.addQuote(MarkdownTools.getCommentsFromElement(element.getElement())));
		}
	}	
	/**
	 * Method to directly initialise the markdown text of the visitor, in order to let it add its generated text and return it to the model descriptor
	 * @param aBuilder {@code StringBuilder}, the StringBuilder of a model descriptor that will receive the generated text
	 */
	public void setText(StringBuilder aBuilder)
	{
		mDText=aBuilder;
	}
	/**
	 * Function that returns the StringBuilder of a VisitorParameters once the visitor has done its job (adding text of a parameter)
	 * @return {@code StringBuilder} the StringBuilder of a model descriptor 
	 */
	public StringBuilder getText()
	{
		return mDText;
	}
	/**
	 * Method to dispose all the objects that have been used by the VisitorParameters and release memory
	 */
	public void dispose()
	{
		this.mDText=null;
	}
}
