// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package ras506;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class __HECRASController_Event_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return ras506.__HECRASController_Event_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        ras506.__HECRASController_Event_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class ____HECRASController_Event extends system.Object implements ras506.__HECRASController_Event {
    
    protected ____HECRASController_Event(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
}
//</generated-proxy>
