// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package ras506;

@net.sf.jni4net.attributes.ClrType
public abstract class __HECRASController_ComputeCompleteEventHandler extends system.MulticastDelegate {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected __HECRASController_ComputeCompleteEventHandler(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected __HECRASController_ComputeCompleteEventHandler() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public abstract void Invoke();
    
    public static system.Type typeof() {
        return ras506.__HECRASController_ComputeCompleteEventHandler.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        ras506.__HECRASController_ComputeCompleteEventHandler.staticType = staticType;
    }
    //</generated-proxy>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class ____HECRASController_ComputeCompleteEventHandler extends ras506.__HECRASController_ComputeCompleteEventHandler {
    
    protected ____HECRASController_ComputeCompleteEventHandler(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Invoke();
}
//</generated-proxy>
