// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package ras506;

@net.sf.jni4net.attributes.ClrInterface
public interface _HECRASGeometry {
    
    //<generated-interface>
    @net.sf.jni4net.attributes.ClrMethod("()I")
    int nRiver();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)LSystem/String;")
    java.lang.String RiverName(net.sf.jni4net.Ref<java.lang.Integer> riv);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)I")
    int RiverIndex(net.sf.jni4net.Ref<java.lang.String> RiverName);
    
    @net.sf.jni4net.attributes.ClrMethod("(I)I")
    int nReach(net.sf.jni4net.Ref<java.lang.Integer> riv);
    
    @net.sf.jni4net.attributes.ClrMethod("(II)LSystem/String;")
    java.lang.String ReachName(net.sf.jni4net.Ref<java.lang.Integer> riv, net.sf.jni4net.Ref<java.lang.Integer> rch);
    
    @net.sf.jni4net.attributes.ClrMethod("(ILSystem/String;)I")
    int ReachIndex(net.sf.jni4net.Ref<java.lang.Integer> riv, net.sf.jni4net.Ref<java.lang.String> ReachName);
    
    @net.sf.jni4net.attributes.ClrMethod("(II)I")
    int ReachInvert_nPoints(net.sf.jni4net.Ref<java.lang.Integer> riv, net.sf.jni4net.Ref<java.lang.Integer> rch);
    
    @net.sf.jni4net.attributes.ClrMethod("(IILSystem/Array;LSystem/Array;)V")
    void ReachInvert_Points(net.sf.jni4net.Ref<java.lang.Integer> riv, net.sf.jni4net.Ref<java.lang.Integer> rch, net.sf.jni4net.Ref<system.Array> PointX, net.sf.jni4net.Ref<system.Array> PointY);
    
    @net.sf.jni4net.attributes.ClrMethod("(II)I")
    int nNode(net.sf.jni4net.Ref<java.lang.Integer> riv, net.sf.jni4net.Ref<java.lang.Integer> rch);
    
    @net.sf.jni4net.attributes.ClrMethod("(III)LSystem/String;")
    java.lang.String NodeRS(net.sf.jni4net.Ref<java.lang.Integer> riv, net.sf.jni4net.Ref<java.lang.Integer> rch, net.sf.jni4net.Ref<java.lang.Integer> n);
    
    @net.sf.jni4net.attributes.ClrMethod("(IILSystem/String;)I")
    int NodeIndex(net.sf.jni4net.Ref<java.lang.Integer> riv, net.sf.jni4net.Ref<java.lang.Integer> rch, net.sf.jni4net.Ref<java.lang.String> Rs);
    
    @net.sf.jni4net.attributes.ClrMethod("(III)I")
    int NodeType(net.sf.jni4net.Ref<java.lang.Integer> riv, net.sf.jni4net.Ref<java.lang.Integer> rch, net.sf.jni4net.Ref<java.lang.Integer> n);
    
    @net.sf.jni4net.attributes.ClrMethod("(III)LSystem/String;")
    java.lang.String NodeCType(net.sf.jni4net.Ref<java.lang.Integer> riv, net.sf.jni4net.Ref<java.lang.Integer> rch, net.sf.jni4net.Ref<java.lang.Integer> n);
    
    @net.sf.jni4net.attributes.ClrMethod("(III)I")
    int NodeCutLine_nPoints(net.sf.jni4net.Ref<java.lang.Integer> riv, net.sf.jni4net.Ref<java.lang.Integer> rch, net.sf.jni4net.Ref<java.lang.Integer> n);
    
    @net.sf.jni4net.attributes.ClrMethod("(IIILSystem/Array;LSystem/Array;)V")
    void NodeCutLine_Points(net.sf.jni4net.Ref<java.lang.Integer> riv, net.sf.jni4net.Ref<java.lang.Integer> rch, net.sf.jni4net.Ref<java.lang.Integer> n, net.sf.jni4net.Ref<system.Array> PointX, net.sf.jni4net.Ref<system.Array> PointY);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    void Save();
    //</generated-interface>
}
