// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package ras506;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class HECRASController_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return ras506.HECRASController_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        ras506.HECRASController_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __HECRASController extends system.Object implements ras506.HECRASController {
    
    protected __HECRASController(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void QuitRas();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Compute_HideComputationWindow();
    
    @net.sf.jni4net.attributes.ClrMethod("(ILSystem/Array;Z)Z")
    public native boolean Compute_CurrentPlan(net.sf.jni4net.Ref<java.lang.Integer> nmsg, net.sf.jni4net.Ref<system.Array> Msg, net.sf.jni4net.Ref<java.lang.Boolean> BlockingMode);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void Project_Open(java.lang.String projectFilename);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Project_Close();
}
//</generated-proxy>
