//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAS506 {
    
    
    #region Component Designer generated code 
    public partial class @__HECRASController_SinkHelper_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::RAS506.____HECRASController_SinkHelper.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::RAS506.@__HECRASController_SinkHelper), typeof(global::RAS506.@__HECRASController_SinkHelper_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::RAS506.@__HECRASController_SinkHelper), typeof(global::RAS506.@__HECRASController_SinkHelper_))]
    internal sealed partial class ____HECRASController_SinkHelper : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private ____HECRASController_SinkHelper(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::RAS506.____HECRASController_SinkHelper.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(____HECRASController_SinkHelper);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ComputeProgressEvent", "ComputeProgressEvent0", "(F)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ComputeMessageEvent", "ComputeMessageEvent1", "(Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ComputeComplete", "ComputeComplete2", "()V"));
            return methods;
        }
        
        private static void ComputeProgressEvent0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, float Progress) {
            // (F)V
            // (F)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RAS506.@__HECRASController_SinkHelper @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::RAS506.@__HECRASController_SinkHelper>(@__env, @__obj);
            ((global::RAS506.@__HECRASController)(@__real)).ComputeProgressEvent(Progress);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void ComputeMessageEvent1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle eventMessage) {
            // (Ljava/lang/String;)V
            // (LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RAS506.@__HECRASController_SinkHelper @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::RAS506.@__HECRASController_SinkHelper>(@__env, @__obj);
            ((global::RAS506.@__HECRASController)(@__real)).ComputeMessageEvent(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, eventMessage));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void ComputeComplete2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RAS506.@__HECRASController_SinkHelper @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::RAS506.@__HECRASController_SinkHelper>(@__env, @__obj);
            ((global::RAS506.@__HECRASController)(@__real)).ComputeComplete();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::RAS506.____HECRASController_SinkHelper(@__env);
            }
        }
    }
    #endregion
}
