//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAS506 {
    
    
    #region Component Designer generated code 
    public partial class _HECRASController_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::RAS506.___HECRASController.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::RAS506._HECRASController), typeof(global::RAS506._HECRASController_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::RAS506._HECRASController), typeof(global::RAS506._HECRASController_))]
    internal sealed partial class ___HECRASController : global::java.lang.Object, global::RAS506._HECRASController {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_QuitRas0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_Compute_ShowComputationWindow1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_Compute_CurrentPlan2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_Project_Open3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_Project_Save4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_Project_Close5;
        
        private ___HECRASController(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::RAS506.___HECRASController.staticClass = @__class;
            global::RAS506.___HECRASController.j4n_QuitRas0 = @__env.GetMethodID(global::RAS506.___HECRASController.staticClass, "QuitRas", "()V");
            global::RAS506.___HECRASController.j4n_Compute_ShowComputationWindow1 = @__env.GetMethodID(global::RAS506.___HECRASController.staticClass, "Compute_ShowComputationWindow", "()V");
            global::RAS506.___HECRASController.j4n_Compute_CurrentPlan2 = @__env.GetMethodID(global::RAS506.___HECRASController.staticClass, "Compute_CurrentPlan", "(Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;)Z");
            global::RAS506.___HECRASController.j4n_Project_Open3 = @__env.GetMethodID(global::RAS506.___HECRASController.staticClass, "Project_Open", "(Ljava/lang/String;)V");
            global::RAS506.___HECRASController.j4n_Project_Save4 = @__env.GetMethodID(global::RAS506.___HECRASController.staticClass, "Project_Save", "()V");
            global::RAS506.___HECRASController.j4n_Project_Close5 = @__env.GetMethodID(global::RAS506.___HECRASController.staticClass, "Project_Close", "()V");
        }
        
        public void QuitRas() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::RAS506.___HECRASController.j4n_QuitRas0);
            }
        }
        
        public void Compute_ShowComputationWindow() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::RAS506.___HECRASController.j4n_Compute_ShowComputationWindow1);
            }
        }
        
        public bool Compute_CurrentPlan(int nmsg, global::System.Array Msg, bool BlockingMode) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return ((bool)(@__env.CallBooleanMethod(this, global::RAS506.___HECRASController.j4n_Compute_CurrentPlan2, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(nmsg), global::net.sf.jni4net.utils.Convertor.ParStrongC2Jp<global::System.Array>(@__env, Msg), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(BlockingMode))));
            }
        }
        
        public void Project_Open(string projectFilename) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::RAS506.___HECRASController.j4n_Project_Open3, global::net.sf.jni4net.utils.Convertor.ParStrongC2JString(@__env, projectFilename));
            }
        }
        
        public void Project_Save() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::RAS506.___HECRASController.j4n_Project_Save4);
            }
        }
        
        public void Project_Close() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::RAS506.___HECRASController.j4n_Project_Close5);
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(___HECRASController);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "QuitRas", "QuitRas0", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Compute_ShowComputationWindow", "Compute_ShowComputationWindow1", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Compute_CurrentPlan", "Compute_CurrentPlan2", "(Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;)Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Project_Open", "Project_Open3", "(Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Project_Save", "Project_Save4", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Project_Close", "Project_Close5", "()V"));
            return methods;
        }
        
        private static void QuitRas0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RAS506._HECRASController @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RAS506._HECRASController>(@__env, @__obj);
            @__real.QuitRas();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Compute_ShowComputationWindow1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RAS506._HECRASController @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RAS506._HECRASController>(@__env, @__obj);
            @__real.Compute_ShowComputationWindow();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static bool Compute_CurrentPlan2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle nmsg, global::net.sf.jni4net.utils.JniLocalHandle Msg, global::net.sf.jni4net.utils.JniLocalHandle BlockingMode) {
            // (Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;Lnet/sf/jni4net/Ref;)Z
            // (ILSystem/Array;Z)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            int @__ref_nmsg = net.sf.jni4net.Ref.GetValue<int>(@__env, nmsg);
            global::System.Array @__ref_Msg = net.sf.jni4net.Ref.GetValue<global::System.Array>(@__env, Msg);
            bool @__ref_BlockingMode = net.sf.jni4net.Ref.GetValue<bool>(@__env, BlockingMode);
            global::RAS506._HECRASController @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RAS506._HECRASController>(@__env, @__obj);
            @__return = ((bool)(@__real.Compute_CurrentPlan(ref __ref_nmsg, ref __ref_Msg, ref __ref_BlockingMode)));
            net.sf.jni4net.Ref.SetValue<int>(@__env, nmsg, @__ref_nmsg);
            net.sf.jni4net.Ref.SetValue<global::System.Array>(@__env, Msg, @__ref_Msg);
            net.sf.jni4net.Ref.SetValue<bool>(@__env, BlockingMode, @__ref_BlockingMode);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Project_Open3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle projectFilename) {
            // (Ljava/lang/String;)V
            // (LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RAS506._HECRASController @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RAS506._HECRASController>(@__env, @__obj);
            @__real.Project_Open(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, projectFilename));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Project_Save4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RAS506._HECRASController @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RAS506._HECRASController>(@__env, @__obj);
            @__real.Project_Save();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Project_Close5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RAS506._HECRASController @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RAS506._HECRASController>(@__env, @__obj);
            @__real.Project_Close();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::RAS506.___HECRASController(@__env);
            }
        }
    }
    #endregion
}
